base_url = "https://kyawaway.github.io/myblog/"
compile_sass = true
# highlight_code = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "monokai"

[languages.en]
title = "遊び日記"
description = "遊びの日記"
# generate_feed = true
# compile_sass = true
taxonomies = [
    {name = "tags"},
]


[languages.en.translations]
language_name = "English"
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"


[extra.social]
github = "kyawaway"
twitter = "kyawaway"

[extra.show]
tags = true
links = true
