# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: checkout
        uses: actions/checkout@v3.0.0
        with:
        submodules: true
    - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
        # Target repository
        REPOSITORY: st-little/st-little.github.io
        # Target branch
        PAGES_BRANCH: gh-pages
        # Build directory
        BUILD_DIR: my_site
        # Provide personal access token
        TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        # Or if publishing to the same repo, use the automatic token
        #TOKEN: ${{ secrets.GITHUB_TOKEN }}
